package org.tiamat.mapper;

import org.apache.ibatis.annotations.Param;
import org.tiamat.model.Employee;

import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    int deleteByPrimaryKey(Integer employeeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    Employee selectByPrimaryKey(Integer employeeid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table employee
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    int updateByPrimaryKey(Employee record);

    /**
     * 查询所有员工
     */
    List<Employee> queryEmployeeAll(Employee employee);

    /**
     * 根据用户名和密码查询用户信息
     */
    Employee queryEmployeeByNameAndPassword(@Param("username") String username, @Param("password") String password);
}