package org.tiamat.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.AdminID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer adminid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Name
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String name;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Gender
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String gender;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Photo
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String photo;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.ContactNumber
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String contactnumber;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Username
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String username;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.Password
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.AdminID
     *
     * @return the value of admin.AdminID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.AdminID
     *
     * @param adminid the value for admin.AdminID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Name
     *
     * @return the value of admin.Name
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Name
     *
     * @param name the value for admin.Name
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Gender
     *
     * @return the value of admin.Gender
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Gender
     *
     * @param gender the value for admin.Gender
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Photo
     *
     * @return the value of admin.Photo
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Photo
     *
     * @param photo the value for admin.Photo
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setPhoto(String photo) {
        this.photo = photo == null ? null : photo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.ContactNumber
     *
     * @return the value of admin.ContactNumber
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getContactnumber() {
        return contactnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.ContactNumber
     *
     * @param contactnumber the value for admin.ContactNumber
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setContactnumber(String contactnumber) {
        this.contactnumber = contactnumber == null ? null : contactnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Username
     *
     * @return the value of admin.Username
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Username
     *
     * @param username the value for admin.Username
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.Password
     *
     * @return the value of admin.Password
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.Password
     *
     * @param password the value for admin.Password
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}