package org.tiamat.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Attendance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.RecordID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer recordid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.EmployeeID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer employeeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.Date
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd")//后端传的日期格式化
    private Date date;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.StartTime
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "HH:mm:ss")//接收页面输入的时间，将其格式化
    @JSONField(format = "HH:mm:ss")//后端传的日期格式化
    private Date starttime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.EndTime
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "HH:mm:ss")//接收页面输入的时间，将其格式化
    @JSONField(format = "HH:mm:ss")//后端传的日期格式化
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.RecordID
     *
     * @return the value of attendance.RecordID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.RecordID
     *
     * @param recordid the value for attendance.RecordID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.EmployeeID
     *
     * @return the value of attendance.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.EmployeeID
     *
     * @param employeeid the value for attendance.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.Date
     *
     * @return the value of attendance.Date
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.Date
     *
     * @param date the value for attendance.Date
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.StartTime
     *
     * @return the value of attendance.StartTime
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.StartTime
     *
     * @param starttime the value for attendance.StartTime
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.EndTime
     *
     * @return the value of attendance.EndTime
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.EndTime
     *
     * @param endtime the value for attendance.EndTime
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}