package org.tiamat.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Eventlog implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eventlog
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.LogID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer logid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.UserID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer userid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.EventType
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String eventtype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.Timestamp
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd HH:mm:ss")//后端传的日期格式化
    private Date timestamp;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.Description
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String description;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eventlog.Remarks
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.LogID
     *
     * @return the value of eventlog.LogID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.LogID
     *
     * @param logid the value for eventlog.LogID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setLogid(Integer logid) {
        this.logid = logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.UserID
     *
     * @return the value of eventlog.UserID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.UserID
     *
     * @param userid the value for eventlog.UserID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.EventType
     *
     * @return the value of eventlog.EventType
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getEventtype() {
        return eventtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.EventType
     *
     * @param eventtype the value for eventlog.EventType
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEventtype(String eventtype) {
        this.eventtype = eventtype == null ? null : eventtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.Timestamp
     *
     * @return the value of eventlog.Timestamp
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getTimestamp() {
        return timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.Timestamp
     *
     * @param timestamp the value for eventlog.Timestamp
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.Description
     *
     * @return the value of eventlog.Description
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.Description
     *
     * @param description the value for eventlog.Description
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eventlog.Remarks
     *
     * @return the value of eventlog.Remarks
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eventlog.Remarks
     *
     * @param remarks the value for eventlog.Remarks
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}