package org.tiamat.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.util.Date;

public class Leave implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table leave
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.LeaveID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer leaveid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.EmployeeID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer employeeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.LeaveType
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private String leavetype;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.StartDate
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd")//后端传的日期格式化
    private Date startdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column leave.EndDate
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd")//后端传的日期格式化
    private Date enddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.LeaveID
     *
     * @return the value of leave.LeaveID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getLeaveid() {
        return leaveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.LeaveID
     *
     * @param leaveid the value for leave.LeaveID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setLeaveid(Integer leaveid) {
        this.leaveid = leaveid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.EmployeeID
     *
     * @return the value of leave.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.EmployeeID
     *
     * @param employeeid the value for leave.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.LeaveType
     *
     * @return the value of leave.LeaveType
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public String getLeavetype() {
        return leavetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.LeaveType
     *
     * @param leavetype the value for leave.LeaveType
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setLeavetype(String leavetype) {
        this.leavetype = leavetype == null ? null : leavetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.StartDate
     *
     * @return the value of leave.StartDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getStartdate() {
        return startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.StartDate
     *
     * @param startdate the value for leave.StartDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column leave.EndDate
     *
     * @return the value of leave.EndDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getEnddate() {
        return enddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column leave.EndDate
     *
     * @param enddate the value for leave.EndDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
}