package org.tiamat.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Overtime implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table overtime
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.OvertimeID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer overtimeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.EmployeeID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer employeeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.OvertimeDate
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd")//后端传的日期格式化
    private Date overtimedate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column overtime.OvertimeDuration
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal overtimeduration;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.OvertimeID
     *
     * @return the value of overtime.OvertimeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getOvertimeid() {
        return overtimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.OvertimeID
     *
     * @param overtimeid the value for overtime.OvertimeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setOvertimeid(Integer overtimeid) {
        this.overtimeid = overtimeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.EmployeeID
     *
     * @return the value of overtime.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.EmployeeID
     *
     * @param employeeid the value for overtime.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.OvertimeDate
     *
     * @return the value of overtime.OvertimeDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getOvertimedate() {
        return overtimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.OvertimeDate
     *
     * @param overtimedate the value for overtime.OvertimeDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setOvertimedate(Date overtimedate) {
        this.overtimedate = overtimedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overtime.OvertimeDuration
     *
     * @return the value of overtime.OvertimeDuration
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getOvertimeduration() {
        return overtimeduration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overtime.OvertimeDuration
     *
     * @param overtimeduration the value for overtime.OvertimeDuration
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setOvertimeduration(BigDecimal overtimeduration) {
        this.overtimeduration = overtimeduration;
    }
}