package org.tiamat.model;

import com.alibaba.fastjson.annotation.JSONField;
import org.springframework.format.annotation.DateTimeFormat;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Salary implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table salary
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.RecordID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer recordid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.EmployeeID
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private Integer employeeid;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.PaymentDate
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")//接收页面输入的时间，将其格式化
    @JSONField(format = "yyyy-MM-dd")//后端传的日期格式化
    private Date paymentdate;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.BasicSalary
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal basicsalary;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.OvertimeSalary
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal overtimesalary;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.Bonus
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal bonus;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.Deduction
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal deduction;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column salary.NetSalary
     *
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    private BigDecimal netsalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.RecordID
     *
     * @return the value of salary.RecordID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.RecordID
     *
     * @param recordid the value for salary.RecordID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.EmployeeID
     *
     * @return the value of salary.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Integer getEmployeeid() {
        return employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.EmployeeID
     *
     * @param employeeid the value for salary.EmployeeID
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setEmployeeid(Integer employeeid) {
        this.employeeid = employeeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.PaymentDate
     *
     * @return the value of salary.PaymentDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public Date getPaymentdate() {
        return paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.PaymentDate
     *
     * @param paymentdate the value for salary.PaymentDate
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setPaymentdate(Date paymentdate) {
        this.paymentdate = paymentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.BasicSalary
     *
     * @return the value of salary.BasicSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.BasicSalary
     *
     * @param basicsalary the value for salary.BasicSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setBasicsalary(BigDecimal basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.OvertimeSalary
     *
     * @return the value of salary.OvertimeSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getOvertimesalary() {
        return overtimesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.OvertimeSalary
     *
     * @param overtimesalary the value for salary.OvertimeSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setOvertimesalary(BigDecimal overtimesalary) {
        this.overtimesalary = overtimesalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.Bonus
     *
     * @return the value of salary.Bonus
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.Bonus
     *
     * @param bonus the value for salary.Bonus
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setBonus(BigDecimal bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.Deduction
     *
     * @return the value of salary.Deduction
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getDeduction() {
        return deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.Deduction
     *
     * @param deduction the value for salary.Deduction
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setDeduction(BigDecimal deduction) {
        this.deduction = deduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column salary.NetSalary
     *
     * @return the value of salary.NetSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public BigDecimal getNetsalary() {
        return netsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column salary.NetSalary
     *
     * @param netsalary the value for salary.NetSalary
     * @mbggenerated Fri Jun 23 13:34:01 CST 2023
     */
    public void setNetsalary(BigDecimal netsalary) {
        this.netsalary = netsalary;
    }
}